version: '3.11'
services:
 # 1. First Container: Django
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  # 2. Second Container: PostgreSQL
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    ports:
#      - 80:8000
      - "8000:8000"
    depends_on:
      - app
    volumes:
      - static_data:/vol/static

volumes:
  postgres_data:
  static_data:
